version: '3.8'

services:
  db:
    container_name: paturo-db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_DB: paturo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data_paturo:/var/lib/postgresql/data

volumes:
  db_data_paturo:
